# Generated by Django 4.2.7 on 2023-11-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=20)),
                ("user_id", models.CharField(max_length=20)),
                ("user_pw", models.CharField(max_length=20)),
                ("user_phone_number", models.CharField(max_length=20)),
                ("user_email", models.CharField(max_length=20)),
            ],
        ),
    ]
