# Generated by Django 4.2.7 on 2023-11-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=20)),
                ("user_pw", models.CharField(max_length=20)),
                ("user_birth_date", models.DateField()),
                ("user_email", models.EmailField(max_length=254)),
                ("user_address", models.CharField(max_length=200)),
                ("user_tel", models.CharField(max_length=20)),
            ],
        ),
    ]
