# Generated by Django 4.2.7 on 2023-11-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventory_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="product_name",
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
