# Generated by Django 4.2.7 on 2023-11-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_inventory_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="size",
        ),
    ]
